Traceback (most recent call last):
  File "XGB_Balanced_EWS_all.py", line 263, in <module>
    clf_hist  = clf_model.fit(X_train, y_train)
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/core.py", line 532, in inner_f
    return f(**kwargs)
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/sklearn.py", line 1400, in fit
    self._Booster = train(
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/core.py", line 532, in inner_f
    return f(**kwargs)
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/training.py", line 181, in train
    bst.update(dtrain, i, obj)
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/core.py", line 1733, in update
    _check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
  File "/home/d/dlr10/anaconda3/envs/spyder-env/lib/python3.8/site-packages/xgboost/core.py", line 203, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: Invalid Input: 'grow_local_histmaker', valid values are: {'approx', 'auto', 'exact', 'gpu_hist', 'hist'}
